schemaVersion: "2.0.0"

commandTests:
  - name: "it says hello"
    command: "sh"
    args:
      - "./docker-entrypoint.sh"
    expectedOutput:
      - "hello"

fileExistenceTests:
  - name: "date file exists"
    path: "/tmp/date.log"
    shouldExist: true
    permissions: "-rw-r--r--"

metadataTest:
  env:
    - key: "STAGE"
      value: "dev"
  labels:
    - key: "maintainer"
      value: "tsubasaogawa"
  exposedPorts: []
  volumes: []
  entrypoint:
    - "sh"
    - "./docker-entrypoint.sh"
  cmd: []
  workdir: "/root"

